# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x, 17.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v1
      with:
        node-version: 16
        always-auth: true
        node-version: ‘14.x’
        registry-url: https://npm.pkg.github.com/
    # - name: Install ts template dependencies using a safe clean install
    - run: cd ts && npm ci
      env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    # - run: cd ts && npm ci
    # - run: cd esm && npm ci
    # - run: cd cjs && npm ci


